### ISSUE TITLE
[compose] Mount fixtures directory to Django container

### ISSUE THREAD

**Issue by smayya337** [HackTJ/live#30]
We should use a bind mount or volume to connect the `judge/fixtures` directory to the Django container so that adding new data is a matter of simply uploading the JSON to the directory and running `docker-compose exec django poetry run python manage.py loaddata 'my-data'` (and not `docker cp ~/live/judge/fixtures/my-data $(bash -c "docker container ls | grep -o live_django_.*"):/app/judge/fixtures` first).

**Comment by sumanthratna** [comment]
I trust volumes more than bind mounts but this shouldn't make much of a difference

**Comment by smayya337** [comment]
I'm more comfortable with bind mounts than volumes, as it turns out. Agreed on the "not making much of a difference" part - as long as it gets implemented somehow we should be good.

**Comment by sumanthratna** [comment]
@smayya337 just fyi, from [docker's docs](https://docs.docker.com/storage/volumes/):
> Volumes are the preferred mechanism for persisting data generated by and used by Docker containers. 

still, shouldn't make much of a difference (I doubt bind mounts will be deprecated any time soon) so do whatever you think is best + easiest

**Comment by smayya337** [comment]
@sumanthratna should be completed with [this commit](https://github.com/HackTJ/live/commit/b81d8a94c03868229aa4c98de037a5a4f4a2b9c9).
